CREATE TABLE CLIENTS
(
    ID      VARCHAR(36)  NOT NULL,
    NAME    VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    PHONE   NUMBER(9) NOT NULL,
    CONSTRAINT PK_CLIENTS PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS
(
    ID              VARCHAR(36)  NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    COUNTRY         CHAR(2)      NOT NULL,
    PRICE           NUMBER(4) NOT NULL,
    EXPIRATION_DATE DATE         NOT NULL,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID)
);

CREATE TABLE INVOICES
(
    ID            VARCHAR(36) NOT NULL,
    CLIENT_ID     VARCHAR(36) NOT NULL,
    CREATION_DATE TIMESTAMP(6) DEFAULT SYSDATE,
    SUMMARY_PRICE NUMBER (9) NOT NULL,
    CONSTRAINT PK_INVOICES PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS
);

CREATE TABLE INVOICE_PRODUCTS
(
    ID            VARCHAR(36) NOT NULL,
    INVOICE_ID    VARCHAR(36) NOT NULL,
    PRODUCT_ID    VARCHAR(36) NOT NULL,
    PRODUCT_COUNT NUMBER(3) NOT NULL,
    PRODUCT_PRICE NUMBER(4) NOT NULL,
    CONSTRAINT PK_INVOICE_PRODUCTS PRIMARY KEY (ID),
    CONSTRAINT FK_INVOICE_ID FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS
);