CREATE TABLE FTP_CONFIG
(
    ID                 VARCHAR(36)  NOT NULL,
    NAME               VARCHAR(100) NOT NULL,
    SERVER_ADDRESS     VARCHAR(100) NOT NULL,
    SERVER_LOGIN       VARCHAR(100) NOT NULL,
    SERVER_PASSWORD    VARCHAR(100) NOT NULL,
    SERVER_PORT        NUMBER(2) NOT NULL,
    SCHEDULING_ENABLED NUMBER(1) NOT NULL,
    CONSTRAINT PK_FTP_CONFIG PRIMARY KEY (ID)
);
