CREATE TABLE CLIENT
(
    ID      VARCHAR(36)  NOT NULL,
    NAME    VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    PHONE   NUMBER(9) NOT NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT
(
    ID              VARCHAR(36)  NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    COUNTRY         CHAR(2)      NOT NULL,
    PRICE           NUMBER(4) NOT NULL,
    EXPIRATION_DATE DATE         NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE INVOICE
(
    ID            VARCHAR(36) NOT NULL,
    CLIENT_ID     VARCHAR(36) NOT NULL,
    CREATION_DATE TIMESTAMP(6) DEFAULT SYSDATE,
    SUMMARY_PRICE NUMBER (9) NOT NULL,
    CONSTRAINT PK_INVOICE PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID) ON DELETE CASCADE
);

CREATE TABLE INVOICE_PRODUCT
(
    ID            VARCHAR(36) NOT NULL,
    INVOICE_ID    VARCHAR(36) NOT NULL,
    PRODUCT_ID    VARCHAR(36) NOT NULL,
    PRODUCT_COUNT NUMBER(3) NOT NULL,
    PRODUCT_PRICE NUMBER(4) NOT NULL,
    CONSTRAINT PK_INVOICE_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_INVOICE_ID FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT
);